
#
# This is free software, lisence use MIT.
# 
# Copyright (C) 2020 KFERMercer <KFER.Mercer@gmail.com>
# 
# <https://github.com/KFERMercer/OpenWrt-CI>
#

name: Update-serverchan-1

on:
# 定时触发
  schedule:
    - cron: 0 18 * * *

# release触发
#  release:
#    types: [published]

# 点赞触发
  watch:
    types: [started]

# 编辑触发
  push:
   branches: 
     - master

# config触发
#  paths:
#    - 'x86_64.config'

jobs:

  prepare:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@master
      with:
        ref: master
        fetch-depth: 0
        lfs: true

    - name: Set git identity
      run : |
        git config --global user.email "KFER.Mercer@gmail.com"
        git config --global user.name "KFERMercer"
    - name: Load latest luci-app-serverchan
      run: |
        git clone https://github.com/tty228/luci-app-serverchan.git --depth=1 ./tmp/luci-app-serverchan
        cp -rf ./tmp/luci-app-serverchan ./
    - name: Apply commit changes
      run: |
        git add ./luci-app-serverchan/
        echo -e "[bot] luci-app-serverchan: update\n\nlatest commit: $(cat ./tmp/luci-app-serverchan/.git/refs/heads/master)" > ./tmp/message
        git commit --file="./tmp/message" --author="github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>" || exit 0
    - name: Push Commits
      run: git push origin master
